### ISSUE TITLE
Problem with colors

### ISSUE THREAD

**Issue by fkozemelj** [imilakovic/IMDrawersMenuController#1]
Hi Igor,

I have few problems with the menu colors and the message it sends. Excluding the black color, I feel like you're encouraging racism and you're being part of the problem.

Regards,

Chantel

**Comment by imilakovic** [comment]
Dear Mrs. Skingrinder,

given the violent nature of your last name, I have no other options but to close this issue. If the problem persists, please feel free to reach us at noreply@noonecares.com

Thank you!

Kind regards,
Igor
